# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - contacts-api-dimensa

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_f41925bbd64648e8b7df8ad19164723a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fc8e1bc0994046e2beaea49834982be3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f41925bbd64648e8b7df8ad19164723a }}/rafaelfernandezcampos/contacts-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'contacts-api-dimensa'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_367a885bd7fa470c9bf8902982e3fa80 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f41925bbd64648e8b7df8ad19164723a }}/rafaelfernandezcampos/contacts-api:${{ github.sha }}'